{{- if (and .Values.persistence.enabled .Values.persistence.kanister.enabled) }}
apiVersion: integration.rock8s.com/v1beta1
kind: Plug
metadata:
  name: kanister-<<APPLICATION>>
  labels:
    app.kubernetes.io/name: {{ template "<<APPLICATION>>.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  epoch: {{ now | unixEpoch | quote }}
  socket:
    name: kanister
    namespace: kanister
  config:
    blueprint: <<APPLICATION>>
    schedule: {{ .Values.persistence.kanister.schedule | quote }}
    workload: {{ template "<<APPLICATION>>.name" . }}
---
apiVersion: cr.kanister.io/v1alpha1
kind: Blueprint
metadata:
  name: <<APPLICATION>>
actions:
  backup:
    kind: StatefulSet
    outputArtifacts:
      backup:
        keyValue:
          kopiaRoot: "{{"{{"}} .Phases.backup.Output.kopiaRoot {{"}}"}}"
          rootDN: "{{"{{"}} .Phases.backup.Output.rootDN {{"}}"}}"
    phases:
      - func: KubeTask
        name: backup
        objects: {}
        args:
          image: registry.gitlab.com/bitspur/rock8s/images/kanukopia:0.100.0
          namespace: {{ .Release.Namespace }}
          command:
            - /bin/bash
            - -o
            - errexit
            - -o
            - pipefail
            - -c
            - |
              BACKUP_FILE=application.backup
              export KOPIA_PASSWORD='{{"{{"}} .Options.kopiaPassword | default "" | toString {{"}}"}}'
              export PREFIX='{{"{{"}} .Options.prefix | default "{{ .Release.Namespace }}/{{ template "<<APPLICATION>>.name" . }}" | toString {{"}}"}}'
              export PROFILE_JSON='{{"{{"}} toJson .Profile {{"}}"}}'
              rm "$BACKUP_FILE" 2>/dev/null || true

              ##### BACKUP APPLICATION HERE #####
              cat > $BACKUP_FILE
              ###################################

              kanukopia kopia snapshot create "$BACKUP_FILE"
              rm "$BACKUP_FILE"
              KOPIA_ROOT="$(kanukopia kopia snapshot list --json -n1 "$BACKUP_FILE" | jq -r '.[0].rootEntry.obj')"
              kando output kopiaRoot "$KOPIA_ROOT"
  restore:
    kind: StatefulSet
    phases:
      - func: KubeTask
        name: restore
        objects: {}
        args:
          image: registry.gitlab.com/bitspur/rock8s/images/kanukopia:0.100.0
          namespace: {{ .Release.Namespace }}
          command:
            - bash
            - -o
            - errexit
            - -o
            - pipefail
            - -c
            - |
              BACKUP_FILE=application.backup
              export KOPIA_PASSWORD='{{"{{"}} .Options.kopiaPassword | default "" | toString {{"}}"}}'
              export PREFIX='{{"{{"}} .Options.prefix | default "{{ .Release.Namespace }}/{{ template "<<APPLICATION>>.name" . }}" | toString {{"}}"}}'
              export PROFILE_JSON='{{"{{"}} toJson .Profile {{"}}"}}'
              rm "$BACKUP_FILE" 2>/dev/null || true
              KOPIA_ROOT='{{"{{"}} .Options.kopiaRoot | default "" | toString {{"}}"}}'
              if [ "$KOPIA_ROOT" = "" ]; then
                SNAPSHOT_TIME='{{"{{"}} .Options.snapshotTime | default "latest" | toString {{"}}"}}'
                KOPIA_ROOT="$(kanukopia find-snapshot "$SNAPSHOT_TIME")"
              fi
              kanukopia kopia snapshot restore "$KOPIA_ROOT" "$BACKUP_FILE"

              ##### RESTORE APPLICATION HERE #####
              cat $BACKUP_FILE | cat
              ###################################

              rm "$BACKUP_FILE"
  restorefrom:
    inputArtifactNames:
      - backup
    kind: StatefulSet
    phases:
      - func: KubeTask
        name: restorefrom
        objects: {}
        args:
          image: registry.gitlab.com/bitspur/rock8s/images/kanukopia:0.100.0
          namespace: {{ .Release.Namespace }}
          command:
            - bash
            - -o
            - errexit
            - -o
            - pipefail
            - -c
            - |
              BACKUP_FILE=application.backup
              export KOPIA_PASSWORD='{{"{{"}} .Options.kopiaPassword | default "" | toString {{"}}"}}'
              export PREFIX='{{"{{"}} .Options.prefix | default "{{ .Release.Namespace }}/{{ template "<<APPLICATION>>.name" . }}" | toString {{"}}"}}'
              export PROFILE_JSON='{{"{{"}} toJson .Profile {{"}}"}}'
              rm "$BACKUP_FILE" 2>/dev/null || true
              KOPIA_ROOT='{{"{{"}} .ArtifactsIn.backup.KeyValue.kopiaRoot | toString {{"}}"}}'
              kanukopia kopia snapshot restore "$KOPIA_ROOT" "$BACKUP_FILE"

              ##### RESTORE APPLICATION HERE #####
              cat $BACKUP_FILE | cat
              ###################################

              rm "$BACKUP_FILE"
{{- end }}
