{{- if (and .Values.persistence.enabled .Values.persistence.kanister.enabled) }}
apiVersion: integration.rock8s.com/v1beta1
kind: Plug
metadata:
  name: kanister-<<APPLICATION>>
  labels:
    app.kubernetes.io/name: {{ template "<<APPLICATION>>.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  epoch: {{ now | unixEpoch | quote }}
  socket:
    name: kanister
    namespace: kanister
  config:
    blueprint: <<APPLICATION>>
    schedule: {{ .Values.persistence.kanister.schedule | quote }}
    workload: {{ template "<<APPLICATION>>.name" . }}
---
apiVersion: cr.kanister.io/v1alpha1
kind: Blueprint
metadata:
  name: <<APPLICATION>>
actions:
  backup:
    kind: StatefulSet
    outputArtifacts:
      backup:
        keyValue:
          snapshot: "{{"{{"}} .Phases.backup.Output.snapshot {{"}}"}}"
          rootDN: "{{"{{"}} .Phases.backup.Output.rootDN {{"}}"}}"
    phases:
      - func: KubeTask
        name: backup
        objects: {}
        args:
          image: registry.gitlab.com/bitspur/rock8s/images/kanukopia:0.100.0
          namespace: {{ .Release.Namespace }}
          command:
            - /bin/bash
            - -o
            - errexit
            - -o
            - pipefail
            - -c
            - |
              BACKUP_FILE=application.backup
              export PASSWORD='{{"{{"}} .Options.password | default "" | toString {{"}}"}}'
              export PREFIX='{{"{{"}} .Options.prefix | default "{{ .Release.Namespace }}/{{ template "<<APPLICATION>>.name" . }}" | toString {{"}}"}}'
              export KANUKOPIA_DEBUG='{{"{{"}} .Options.debug | default "" | toString {{"}}"}}'
              export PROFILE_JSON='{{"{{"}} toJson .Profile {{"}}"}}'
              rm "$BACKUP_FILE" 2>/dev/null || true

              ##### BACKUP APPLICATION HERE #####
              cat > $BACKUP_FILE
              ###################################

              SNAPSHOT="$(kanukopia restic backup --json "$BACKUP_FILE" | jq -r '.snapshots[0].id')"
              rm "$BACKUP_FILE"
              kando output snapshot "$SNAPSHOT"
  restore:
    kind: StatefulSet
    phases:
      - func: KubeTask
        name: restore
        objects: {}
        args:
          image: registry.gitlab.com/bitspur/rock8s/images/kanukopia:0.100.0
          namespace: {{ .Release.Namespace }}
          command:
            - bash
            - -o
            - errexit
            - -o
            - pipefail
            - -c
            - |
              BACKUP_FILE=application.backup
              export PASSWORD='{{"{{"}} .Options.password | default "" | toString {{"}}"}}'
              export PREFIX='{{"{{"}} .Options.prefix | default "{{ .Release.Namespace }}/{{ template "<<APPLICATION>>.name" . }}" | toString {{"}}"}}'
              export KANUKOPIA_DEBUG='{{"{{"}} .Options.debug | default "" | toString {{"}}"}}'
              export PROFILE_JSON='{{"{{"}} toJson .Profile {{"}}"}}'
              rm "$BACKUP_FILE" 2>/dev/null || true
              SNAPSHOT='{{"{{"}} .Options.snapshot | default "" | toString {{"}}"}}'
              if [ "$SNAPSHOT" = "" ]; then
                SNAPSHOT_TIME='{{"{{"}} .Options.snapshotTime | default "latest" | toString {{"}}"}}'
                SNAPSHOT="$(kanukopia find-snapshot "$SNAPSHOT_TIME")"
              fi
              kanukopia restic restore "$SNAPSHOT" --target "$BACKUP_FILE"

              ##### RESTORE APPLICATION HERE #####
              cat $BACKUP_FILE | cat
              ###################################

              rm "$BACKUP_FILE"
  restorefrom:
    inputArtifactNames:
      - backup
    kind: StatefulSet
    phases:
      - func: KubeTask
        name: restorefrom
        objects: {}
        args:
          image: registry.gitlab.com/bitspur/rock8s/images/kanukopia:0.100.0
          namespace: {{ .Release.Namespace }}
          command:
            - bash
            - -o
            - errexit
            - -o
            - pipefail
            - -c
            - |
              BACKUP_FILE=application.backup
              export PASSWORD='{{"{{"}} .Options.password | default "" | toString {{"}}"}}'
              export PREFIX='{{"{{"}} .Options.prefix | default "{{ .Release.Namespace }}/{{ template "<<APPLICATION>>.name" . }}" | toString {{"}}"}}'
              export KANUKOPIA_DEBUG='{{"{{"}} .Options.debug | default "" | toString {{"}}"}}'
              export PROFILE_JSON='{{"{{"}} toJson .Profile {{"}}"}}'
              rm "$BACKUP_FILE" 2>/dev/null || true
              SNAPSHOT='{{"{{"}} .ArtifactsIn.backup.KeyValue.snapshot | toString {{"}}"}}'
              kanukopia restic restore "$SNAPSHOT" --target "$BACKUP_FILE"

              ##### RESTORE APPLICATION HERE #####
              cat $BACKUP_FILE | cat
              ###################################

              rm "$BACKUP_FILE"
{{- end }}
